# 4.8 Grouping Data & Aggregating Variables

# Contents

### 1. Importing Libaries and Data

### 2. Create a subset / aggregated mean

### 3. Group by

### 4. Creating flags using the transform() and loc() functions

# Script

### 1. Importing Libaries and Data

### Step 1: Create a new notebook for this task. Be sure to import the relevant libraries, along with your ords_prods_merge dataframe

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
#defining path
path = r'C:\Users\tinar\OneDrive\Dokumente\00 DATA ANALYST Carrer Foundry\04 Immersion Course\4. Python Fundamentals for Data Analysts\2209 Instacart Basket Analysis'

In [3]:
# import of orders_products_merged with New Variables from 4.7 
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', '02 Prepared Data', 'orders_products_merged_NV.pkl'))

### 2. Create a subset / aggregated mean

### Step 2 How to find the aggregated mean of the “order_number” column grouped by “department_id” for the entire dataframe

In [19]:
ords_prods_merge.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_time_of_the_day,max_order,loyalty_flag
0,2539329,1,1,2,8,11.11484,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,10,New customer
1,2398795,1,2,3,7,15.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,10,New customer
2,473747,1,3,3,12,21.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,10,New customer
3,2254736,1,4,4,7,29.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Average orders,Average orders,10,New customer
4,431534,1,5,4,15,28.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,10,New customer

### 3. Group by

In [6]:
ords_prods_merge.groupby('product_name')

In [7]:
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

### Step 3: Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.

In [20]:
#Subset 
df = ords_prods_merge[:1000000]

In [21]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

Instead of 1000000 rows we now have analysed all 32404859. Before we only had 8 departments listet, now 21. That leads to a larger data spread.

### 4. Creating flags using the transform() and loc() functions

### Step 4: Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

In [22]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [23]:
pd.options.display.max_rows = None

In [24]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_time_of_the_day,max_order,loyalty_flag
0,2539329,1,1,2,8,11.11484,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,10,New customer
1,2398795,1,2,3,7,15.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,10,New customer
2,473747,1,3,3,12,21.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,10,New customer
3,2254736,1,4,4,7,29.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Average orders,Average orders,10,New customer
4,431534,1,5,4,15,28.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,10,New customer
5,3367565,1,6,2,7,19.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,10,New customer
6,550135,1,7,1,9,20.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,10,New customer
7,3108588,1,8,1,14,14.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,10,New customer
8,2295261,1,9,1,16,0.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,10,New customer
9,2550362,1,10,4,8,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Fewest orders,Fewest orders,10,New customer
10,2968173,15,15,1,9,7.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
11,1870022,15,17,2,16,8.00000,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
12,1911383,15,18,2,11,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
13,2715276,15,21,1,9,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
14,487368,15,22,1,10,14.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
15,2293453,19,2,5,14,6.00000,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,9,New customer
16,1973799,19,5,6,12,8.00000,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,9,New customer
17,532817,19,7,4,17,6.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Average orders,Average orders,9,New customer
18,1573906,21,10,3,10,6.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,33,Regular customer
19,1593000,31,10,3,8,7.00000,196,17,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,20,Regular customer
20,2231262,31,17,3,11,8.00000,196,14,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,20,Regular customer
21,2580647,43,6,4,16,4.00000,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,11,Regular customer
22,2187180,43,9,4,12,3.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,11,Regular customer
23,2497897,52,1,1,9,11.11484,196,4,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
24,1318871,52,2,1,10,7.00000,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
25,1261384,52,3,1,10,7.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
26,580568,52,5,2,10,8.00000,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
27,2428073,52,7,2,7,8.00000,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,27,Regular customer
28,342306,52,9,1,11,7.00000,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
29,1520353,52,10,2,10,8.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
30,2542086,52,11,2,9,7.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
31,944694,52,12,1,16,6.00000,196,7,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
32,1268191,52,15,2,11,8.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
33,1122089,52,17,2,10,6.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
34,1498922,52,18,2,10,14.00000,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
35,180919,52,19,3,8,8.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,27,Regular customer
36,2695875,52,21,5,10,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
37,3205960,67,1,3,11,11.11484,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
38,970922,67,2,1,15,5.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
39,596585,67,3,1,13,7.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
40,2037087,67,4,2,9,8.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
41,2474111,67,5,3,14,8.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
42,1568481,67,6,3,12,7.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
43,2048527,67,8,2,11,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
44,2389031,67,9,2,14,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
45,2378562,67,10,1,10,6.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
46,1515698,67,11,1,11,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
47,1928050,67,12,2,12,8.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
48,1949274,67,13,1,10,6.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
49,551869,67,14,1,9,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
50,768572,67,16,4,10,9.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,24,Regular customer
51,150528,67,18,5,16,4.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
52,29758,67,19,0,14,9.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most orders,Most orders,24,Regular customer
53,1558976,67,21,1,9,5.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
54,863974,67,22,1,11,14.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
55,2308399,67,23,1,14,14.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
56,2759128,81,3,1,9,14.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,7,New customer
57,1812985,81,5,2,20,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,7,New customer
58,1889835,82,1,3,15,11.11484,196,6,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
59,499460,82,3,5,10,5.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
60,2728456,82,4,0,11,16.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most orders,Most orders,19,Regular customer
61,2653743,82,6,4,9,13.00000,196,5,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,19,Regular customer
62,1358880,82,9,1,10,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
63,343588,82,10,2,11,1.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
64,3034663,82,15,2,11,12.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
65,147262,82,18,1,13,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
66,3144004,82,19,2,15,8.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
67,2126069,98,3,0,9,25.00000,196,7,0,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most orders,Most orders,14,Regular customer
68,2210120,98,7,5,14,5.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,14,Regular customer
69,681011,98,9,3,9,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,14,Regular customer
70,2846344,98,11,4,13,15.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,14,Regular customer
71,747431,98,12,6,13,30.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,14,Regular customer
72,2383054,98,13,4,11,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,14,Regular customer
73,1993729,98,14,5,8,8.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,14,Regular customer
74,1403849,109,3,3,17,9.00000,196,5,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,6,New customer
75,520620,120,1,3,11,11.11484,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,3,New customer
76,3273029,120,3,2,8,19.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,3,New customer
77,1861943,185,2,1,12,25.00000,196,10,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,6,New customer
78,2040988,195,1,1,14,11.11484,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
79,1680569,195,8,1,9,4.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
80,276171,195,19,5,11,3.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
81,2744976,195,22,5,10,7.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
82,2781919,195,25,1,14,4.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
83,1738718,195,31,2,8,4.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,58,Loyal customer
84,3058369,195,34,3,10,6.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
85,1485596,195,37,2,15,0.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
86,417035,195,40,3,16,2.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
87,1615297,195,47,5,10,2.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
88,1765587,195,52,3,12,2.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
89,745908,195,57,4,11,3.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,58,Loyal customer
90,2505656,222,17,2,12,1.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,70,Loyal customer
91,3268370,222,38,5,15,1.00000,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,70,Loyal customer
92,2016711,290,9,5,19,6.00000,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,51,Loyal customer
93,2706088,290,28,6,10,7.00000,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,51,Loyal customer
94,1952286,331,6,5,16,30.00000,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,8,New customer
95,3226575,360,1,5,12,11.11484,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,3,New customer
96,1469869,377,3,5,17,3.00000,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,3,New customer
97,1927023,387,2,4,10,22.00000,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,8,New customer
98,858092,420,4,1,19,30.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,22,Regular customer
99,119314,420,5,3,19,16.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,22,Regular customer

In [25]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [26]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [27]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [28]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [29]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_time_of_the_day,max_order,loyalty_flag
0,2539329,1,1,2,8,11.11484,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,10,New customer
1,2398795,1,2,3,7,15.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,10,New customer
2,473747,1,3,3,12,21.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,10,New customer
3,2254736,1,4,4,7,29.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Average orders,Average orders,10,New customer
4,431534,1,5,4,15,28.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,10,New customer
5,3367565,1,6,2,7,19.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,10,New customer
6,550135,1,7,1,9,20.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,10,New customer
7,3108588,1,8,1,14,14.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,10,New customer
8,2295261,1,9,1,16,0.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,10,New customer
9,2550362,1,10,4,8,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Fewest orders,Fewest orders,10,New customer
10,2968173,15,15,1,9,7.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
11,1870022,15,17,2,16,8.00000,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
12,1911383,15,18,2,11,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
13,2715276,15,21,1,9,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
14,487368,15,22,1,10,14.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,22,Regular customer
15,2293453,19,2,5,14,6.00000,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,9,New customer
16,1973799,19,5,6,12,8.00000,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,9,New customer
17,532817,19,7,4,17,6.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Average orders,Average orders,9,New customer
18,1573906,21,10,3,10,6.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,33,Regular customer
19,1593000,31,10,3,8,7.00000,196,17,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,20,Regular customer
20,2231262,31,17,3,11,8.00000,196,14,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,20,Regular customer
21,2580647,43,6,4,16,4.00000,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,11,Regular customer
22,2187180,43,9,4,12,3.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,11,Regular customer
23,2497897,52,1,1,9,11.11484,196,4,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
24,1318871,52,2,1,10,7.00000,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
25,1261384,52,3,1,10,7.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
26,580568,52,5,2,10,8.00000,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
27,2428073,52,7,2,7,8.00000,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,27,Regular customer
28,342306,52,9,1,11,7.00000,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
29,1520353,52,10,2,10,8.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
30,2542086,52,11,2,9,7.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
31,944694,52,12,1,16,6.00000,196,7,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
32,1268191,52,15,2,11,8.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
33,1122089,52,17,2,10,6.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
34,1498922,52,18,2,10,14.00000,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
35,180919,52,19,3,8,8.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,27,Regular customer
36,2695875,52,21,5,10,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,27,Regular customer
37,3205960,67,1,3,11,11.11484,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
38,970922,67,2,1,15,5.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
39,596585,67,3,1,13,7.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
40,2037087,67,4,2,9,8.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
41,2474111,67,5,3,14,8.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
42,1568481,67,6,3,12,7.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
43,2048527,67,8,2,11,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
44,2389031,67,9,2,14,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
45,2378562,67,10,1,10,6.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
46,1515698,67,11,1,11,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
47,1928050,67,12,2,12,8.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
48,1949274,67,13,1,10,6.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
49,551869,67,14,1,9,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
50,768572,67,16,4,10,9.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,24,Regular customer
51,150528,67,18,5,16,4.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
52,29758,67,19,0,14,9.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most orders,Most orders,24,Regular customer
53,1558976,67,21,1,9,5.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
54,863974,67,22,1,11,14.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
55,2308399,67,23,1,14,14.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,24,Regular customer
56,2759128,81,3,1,9,14.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,7,New customer
57,1812985,81,5,2,20,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,7,New customer
58,1889835,82,1,3,15,11.11484,196,6,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
59,499460,82,3,5,10,5.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
60,2728456,82,4,0,11,16.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most orders,Most orders,19,Regular customer
61,2653743,82,6,4,9,13.00000,196,5,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,19,Regular customer
62,1358880,82,9,1,10,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
63,343588,82,10,2,11,1.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
64,3034663,82,15,2,11,12.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
65,147262,82,18,1,13,7.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
66,3144004,82,19,2,15,8.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,19,Regular customer
67,2126069,98,3,0,9,25.00000,196,7,0,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most orders,Most orders,14,Regular customer
68,2210120,98,7,5,14,5.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,14,Regular customer
69,681011,98,9,3,9,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,14,Regular customer
70,2846344,98,11,4,13,15.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,14,Regular customer
71,747431,98,12,6,13,30.00000,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,14,Regular customer
72,2383054,98,13,4,11,30.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,14,Regular customer
73,1993729,98,14,5,8,8.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,14,Regular customer
74,1403849,109,3,3,17,9.00000,196,5,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,6,New customer
75,520620,120,1,3,11,11.11484,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,3,New customer
76,3273029,120,3,2,8,19.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,3,New customer
77,1861943,185,2,1,12,25.00000,196,10,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,6,New customer
78,2040988,195,1,1,14,11.11484,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
79,1680569,195,8,1,9,4.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
80,276171,195,19,5,11,3.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
81,2744976,195,22,5,10,7.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
82,2781919,195,25,1,14,4.00000,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
83,1738718,195,31,2,8,4.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Fewest orders,Fewest orders,58,Loyal customer
84,3058369,195,34,3,10,6.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
85,1485596,195,37,2,15,0.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
86,417035,195,40,3,16,2.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
87,1615297,195,47,5,10,2.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
88,1765587,195,52,3,12,2.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,58,Loyal customer
89,745908,195,57,4,11,3.00000,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,58,Loyal customer
90,2505656,222,17,2,12,1.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,70,Loyal customer
91,3268370,222,38,5,15,1.00000,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,70,Loyal customer
92,2016711,290,9,5,19,6.00000,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,51,Loyal customer
93,2706088,290,28,6,10,7.00000,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,51,Loyal customer
94,1952286,331,6,5,16,30.00000,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,8,New customer
95,3226575,360,1,5,12,11.11484,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most orders,Most orders,3,New customer
96,1469869,377,3,5,17,3.00000,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,3,New customer
97,1927023,387,2,4,10,22.00000,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Most orders,Most orders,8,New customer
98,858092,420,4,1,19,30.00000,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,22,Regular customer
99,119314,420,5,3,19,16.00000,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average orders,Average orders,22,Regular customer

In [18]:
ords_prods_merge.shape

(32404859, 20)

### Step 5: The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified.

In [31]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

From the table above we can see that loyal customer actually go for lower priced products.

### Step 6: The team now wants to target different types of spenders in their marketing campaigns

In [32]:
# Creating a new column called 'avg_price'

ords_prods_merge['avg_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [33]:
# Creating a flag that assigns a “types of spenders” label to a user ID based on average prices.

ords_prods_merge.loc[ords_prods_merge['avg_price'] < 10, 'spender_flag'] = 'Low spender'
ords_prods_merge.loc[ords_prods_merge['avg_price'] >= 10, 'spender_flag'] = 'High spender'

In [34]:
ords_prods_merge['spender_flag'].value_counts(dropna = False)

Low spender     31770614
High spender      634245
Name: spender_flag, dtype: int64

### Step 7: the Instacart team wants you to determine frequent versus non-frequent customers

In [35]:
ords_prods_merge['median_days_since_prior_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [36]:
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order']>20, 'frequency_flag'] = 'Non-frequent customer'
ords_prods_merge.loc[(ords_prods_merge['median_days_since_prior_order']>10) & (ords_prods_merge['median_days_since_prior_order']<=20), 'frequency_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order']<=10, 'frequency_flag'] = 'Frequent customer'

In [37]:
ords_prods_merge['frequency_flag'].value_counts(dropna = False)

Frequent customer        20535136
Regular customer          9168905
Non-frequent customer     2700818
Name: frequency_flag, dtype: int64

### Export

In [39]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','02 Prepared Data','orders_products_merged_48.pkl'))